package Lista02;

/**
 *
 * @author aluno
 */
public class Apolice {
    // Exercicio 2

    
    // atributos
    private int numero;
    private String nome;
    private int idade;
    private char sexo;
    private double valorAutomovel;
    
    
     public Apolice() {
        return Apolice;
    }
    
     public apolice( numero:int,nome:String,idade::int ;
    private int Sexo;
char,valorAutomovel:double){
    
}
    //metodo
    
    public double calcularValor(){
        
        for (int sexo = M; getIdade() >= 25); {
        }
             return getValorAutomovel()*10/100;
         if ( getsexo()=="M" & getIdade()>=25);
               return getValorAutomovel()*5/100;
         &
         if ( getsexo()=="F")
               return getValorAutomovel()*2/100;
        
    }

    /**
     * @return the numero
     */
    public int getNumero() {
        return numero;
    }

    /**
     * @param numero the numero to set
     */
    public void setNumero(int numero) {
        this.numero = numero;
    }

    /**
     * @return the nome
     */
    public String getNome() {
        return nome;
    }

    /**
     * @param nome the nome to set
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * @return the idade
     */
    public int getIdade() {
        return idade;
    }

    /**
     * @param idade the idade to set
     */
    public void setIdade(int idade) {
        this.idade = idade;
    }

    /**
     * @return the sexo
     */
    public char getSexo() {
        return sexo;
    }

    /**
     * @param sexo the sexo to set
     */
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

    /**
     * @return the valorAutomovel
     */
    public double getValorAutomovel() {
        return valorAutomovel;
    }

    /**
     * @param valorAutomovel the valorAutomovel to set
     */
    public void setValorAutomovel(double valorAutomovel) {
        this.valorAutomovel = valorAutomovel;
    }

    /**
     * @return the Sexo
     */
    public int getsexo() {
        return sexo;
    }

    /**
     * @param Sexo the Sexo to set
     */
    public void setSexo(int Sexo) {
        this.Sexo = Sexo;
    }
}

                 // IMPRIMIR
                 public String imprimir(){
                 return "Numero : " + numero +
                 "\nNome :" + nome+
                 "\nIdade :" + idade+
                 "\nSexo :" + sexo+
                 "\nValor Automovel :" + valorAutomovel+
                 "\nValor Apolice :" + apolice;
           
   public String Criarapolice(apolice a){
     
        String retorno = "";
        retorno += "Crie uma apolice";
        retorno += a.Criarapolice();
        return retorno;
    }
    public String Dadosapolice(){
        
        return "Ver dados apolice : "+ apolice;
    }
   
     public String Sair(){
     
        return "Apolice criado : " + apolice;
    }

 
}
         
