//Exercicio 01


package Lista02;

// classe
public class Calculadora {
    
    public static void main(String[] args) {
        
        //atributos
        
        public int Soma;
        public double soma;
        public int subtracao;
        public double subtracao;
        public int multipicacao;
        public double multiplicacao;
        public int divisao;
        public double divisao;
        
    }
      
                  
                  
